# Extras from the official Wegcode (wegcode.be) that are not in the user's 222-list.
# key: ('row',CODE) -> image from Wegcode table row; ('left',idx) -> image from 'left' list.
# value: (EN, TR, cat, note, nl_official)
EX = {
('row','A50'):("Warning: traffic jam (queue) ahead","İleride trafik sıkışıklığı (kuyruk) uyarısı","W","A50: Kuyruğun sonuna yaklaşırken hızı erkenden düşür, dörtlüleri (hazard) yak.","File."),
('row','B22'):("Cyclists may pass the red light to turn right (give way)","Bisikletliler kırmızıda sağa dönebilir (yol vererek)","P","B22: SADECE bisikletliler/speed pedelec için; yol vermek şartıyla kırmızı veya sarı ışıkta sağa dönebilirler. Araçlar için geçerli değildir!","Fietsers mogen door rood om rechts af te slaan."),
('row','B23'):("Cyclists may pass the red light to go straight (give way)","Bisikletliler kırmızıda düz gidebilir (yol vererek)","P","B23: SADECE bisikletliler için; kırmızıda düz geçebilirler, yol vermek zorundalar. Sınav tuzağı: araçlar için değil.","Fietsers mogen door rood rechtdoor."),
('row','C46'):("End of all local prohibitions for moving vehicles","Tüm yerel yasakların sonu (hareket halindeki araçlar için)","C","C46: Önceki yasak levhalarının (hız, sollama vb.) hepsini bitirir.","Einde van alle plaatselijke verbodsbepalingen."),
('row','C47'):("Toll booth: stop before passing","Gişe: geçmeden önce dur (TOL)","C","C47: Ücretli geçiş; durmadan geçmek yasak.","Tolpost."),
('row','D4'):("Vehicles carrying dangerous goods must follow the arrow","Tehlikeli madde taşıyan araçlar oku izlemek zorunda","D","D4: Sadece tehlikeli madde taşıyanlar için zorunlu yön.","Gebod voor voertuigen met gevaarlijke goederen."),
('row','E9b'):("Parking only for motorcycles, cars, dual-purpose vehicles and minibuses","Park yalnız motosiklet, otomobil ve minibüsler için","E","E9b","Parkeren uitsluitend voor motorfietsen, personenauto's, minibussen."),
('row','E9c'):("Parking only for light trucks and trucks","Park yalnız kamyonet ve kamyonlar için","E","E9c","Parkeren uitsluitend voor (lichte) vrachtauto's."),
('row','E9d'):("Parking only for coaches/buses","Park yalnız yolcu otobüsleri (autocar) için","E","E9d","Parkeren uitsluitend voor autocars."),
('row','E9h'):("Parking only for campers","Park yalnız karavan/kamp araçları için","E","E9h","Parkeren uitsluitend voor kampeerauto's."),
('row','E9i'):("Parking only for motorcycles","Park yalnız motosikletler için","E","E9i","Parkeren uitsluitend voor motorfietsen."),
('row','F15'):("Direction choice sign (arrows per lane/direction)","Yön seçimi levhası (şeritlere göre oklar)","I","F15: Okların yönü hangi şeridin nereye gittiğini gösterir.","Verkeersbord dat de keuze van een richting voorschrijft."),
('row','F21'):("Pass either left or right","Sağdan veya soldan geçmek serbest","I","F21: Engelin (ada) iki yanından da geçilebilir.","Rechts of links voorbijrijden toegelaten."),
('row','F23a'):("Road number: ordinary road (N)","Normal yol numarası (N)","I","F23a: Mavi zemin, N = nationale weg.","Nummer van een gewone weg."),
('row','F23b'):("Road number: motorway (A)","Otoyol numarası (A)","I","F23b: Siyah-beyaz A harfi = autosnelweg.","Nummer van een autosnelweg."),
('row','F23c'):("Road number: international road (E)","Uluslararası yol numarası (E)","I","F23c: Yeşil E levhası (ör. E40).","Nummer van een internationale weg."),
('row','F23d'):("Road number: ring road (R)","Çevre yolu numarası (R / Ring)","I","F23d: Ring yolu.","Nummer van een ring."),
('row','F29'):("Direction sign (destination and distance)","Yön tabelası (varış yeri ve mesafe)","I","F29: Yol ayrımında gidilecek yerler.","Wegwijzer."),
('row','F31'):("Direction sign: route via a motorway","Yön tabelası: otoyol üzerinden güzergâh","I","F31: Yeşil = otoyol güzergâhı.","Wegwijzer: reisweg over een autosnelweg."),
('row','F33a'):("Advance direction sign: airport, hospital, port, industrial park, ring, etc.","Mesafeli yönlendirme: havalimanı, hastane, liman, sanayi, ring vb.","I","F33a","Bewegwijzeringsbord op afstand."),
('row','F33b'):("Advance direction sign: scenic valley or river","Mesafeli yönlendirme: turistik vadi/akarsu","I","F33b","Bewegwijzeringsbord: vallei of waterloop."),
('row','F33c'):("Advance direction sign: tourist or recreation site","Mesafeli yönlendirme: turistik/eğlence yeri","I","F33c: Kahverengi = turistik.","Bewegwijzeringsbord: toeristisch of ontspannend karakter."),
('row','F34a'):("Direction sign near public facilities (library, post office...)","Kamu kurumları yakınında yön levhası (kütüphane, postane vb.)","I","F34a","Bewegwijzeringsbord in de nabijheid van openbare inrichtingen."),
('row','F35'):("Direction sign: sports/tourist/recreation destination","Yön levhası: spor/turistik/eğlence hedefi","I","F35","Wegwijzer: sportcentrum, toeristische plaats."),
('row','F37'):("Direction sign: youth hostel, lodging, camping, restaurant","Yön levhası: yurt, konaklama, kamp, restoran","I","F37","Wegwijzer: jeugdherberg, overnachting, restaurant."),
('row','F39'):("Advance sign announcing a detour","Güzergâh değişikliği (yol kapalı) ön uyarısı","I","F39: Turuncu = geçici sapma.","Voorwegwijzer die een omlegging aankondigt."),
('row','F41'):("Detour direction sign","Güzergâh değişikliği yön levhası","I","F41: Turuncu sapma ok işareti.","Wegwijzer, omleggingsweg."),
('row','F43'):("Place-name sign","Yer adı levhası","I","F43: Sarı zemin; yerleşim yeri adını gösterir.","Plaatsnaambord."),
('row','F45b'):("Dead end, except for pedestrians and cyclists","Çıkmaz sokak, yayalar ve bisikletliler hariç","I","F45b: Araçlara çıkmaz, yaya/bisiklet geçebilir.","Doodlopende weg, uitgezonderd voor voetgangers en fietsers."),
('row','F47'):("End of roadworks","Yol çalışmasının sonu","I","F47","Einde van de werken."),
('row','F50bis'):("Turning traffic: watch for cyclists/mopeds going straight","Dönen araçlar: aynı yönde giden bisiklet/mopedlere dikkat","I","F50bis: Sağa dönerken bisiklet yolundakilere yol ver.","Wijst op fietsers die dezelfde weg volgen."),
('row','F51'):("Underground/overhead pedestrian crossing","Yer altı/üst geçit (yayalar için)","I","F51","Ondergrondse of bovengrondse oversteekplaats voor voetgangers."),
('row','F52'):("Announcement of emergency exit in tunnels","Tünelde acil çıkış duyurusu","I","F52: Yeşil: acil çıkış yönü ve mesafe.","Aankondiging van een nooduitgang in tunnels."),
('row','F53'):("Hospital / medical facility","Hastane / sağlık kuruluşu","I","F53","Verplegingsinrichting."),
('row','F55'):("First aid post","İlk yardım noktası","I","F55","Hulppost."),
('row','F56'):("Fire extinguisher","Yangın söndürücü","I","F56","Brandblusapparaat."),
('row','F57'):("Watercourse (river) name","Akarsu adı","I","F57: Köprüde nehir adı.","Waterloop."),
('row','F59'):("Parking announcement","Otopark duyurusu","I","F59","Aankondiging van een parking."),
('row','F60'):("Covered car park announcement","Kapalı otopark duyurusu","I","F60","Aankondiging van een overdekte parking."),
('row','F61'):("Telephone","Telefon","I","F61","Telefoon."),
('row','F62'):("Emergency telephone","Acil durum telefonu (SOS)","I","F62","Noodtelefoon."),
('row','F65'):("Hotel or motel","Otel veya motel","I","F65","Hotel of motel."),
('row','F67'):("Restaurant","Restoran","I","F67","Restaurant."),
('row','F69'):("Refreshments / café","Kafe / içecek yeri","I","F69","Drankgelegenheid."),
('row','F71'):("Campsite","Kamp alanı","I","F71","Kampeerterrein."),
('row','F73'):("Caravan site","Karavan alanı","I","F73","Caravanterrein."),
('row','F75'):("Youth hostel","Gençlik yurdu","I","F75","Jeugdherberg."),
('row','F77'):("Tourist information","Turizm danışma / bilgi noktası","I","F77","Toeristische informatie."),
('row','F79'):("Roadworks: lane reduction ahead","Yol çalışması: şerit sayısı azalıyor","I","F79: Turuncu; mesafe aşağıda yazar.","Vermindering van het aantal rijstroken."),
('row','F81'):("Roadworks: lane shift (diversion) ahead","Yol çalışması: şerit kayması (sapma)","I","F81","Uitwijking."),
('row','F83'):("Roadworks: crossing the median ahead","Yol çalışması: orta refüjden diğer yöne geçiş","I","F83","Doorsteek van de middenberm."),
('row','F85'):("Roadworks: traffic in both directions on part of the carriageway","Yol çalışması: yolun bir kısmında çift yönlü trafik","I","F85","Verkeer in beide richtingen op een deel van de rijbaan."),
('row','F93'):("Radio station with traffic information","Trafik bilgisi veren radyo frekansı","I","F93: Örn. Radio info FM 92.3.","Radio-omroep met verkeersinformatie."),
('row','F98'):("Refuge bay (with SOS telephone)","Acil kaçış/sığınma cebi (SOS telefonu)","I","F98: Tünel/otoyolda sığınma alanı.","Vluchthaven."),
('row','F99a'):("Begin of road reserved for pedestrians, cyclists, riders and speed pedelecs","Yayalar, bisikletliler, binici ve speed pedelec'lere ayrılmış yol başlangıcı","D","F99a: Motorlu trafik giremez.","Begin van de weg voorbehouden voor voetgangers, fietsers, ruiters en speed pedelecs."),
('row','F99b'):("Begin of path reserved for pedestrians and cyclists (divided)","Yaya ve bisikletliler için ayrılmış yol başlangıcı (bölünmüş)","D","F99b","Begin van het deel voorbehouden aan voetgangers en fietsers."),
('row','F99c'):("Begin of road for agricultural vehicles, pedestrians, cyclists, riders","Tarım araçları, yaya, bisiklet ve binicilere ayrılmış yol başlangıcı","D","F99c","Begin van de weg voorbehouden voor landbouwvoertuigen e.a."),
('row','F101a'):("End of road reserved for pedestrians, cyclists, riders and speed pedelecs","Yaya/bisiklet/binici/speed pedelec yolunun sonu","D","F101a","Einde van de weg voorbehouden aan voetgangers, fietsers, ruiters."),
('row','F101b'):("End of path reserved for pedestrians and cyclists","Yaya ve bisiklet yolunun sonu","D","F101b","Einde van het deel voorbehouden aan voetgangers en fietsers."),
('row','F101c'):("End of road for agricultural vehicles, pedestrians, cyclists, riders","Tarım araçları, yaya, bisiklet, binici yolunun sonu","D","F101c","Einde van de weg voor landbouwvoertuigen e.a."),
('row','F117'):("Begin of a low emission zone (LEZ)","Düşük emisyon bölgesi (LEZ) başlangıcı","Z","F117: Gent, Antwerpen ve Brüksel'de LEZ var; aracın Euro normu uygun değilse girilmez.","Begin van een lage emissiezone."),
('row','F118'):("End of a low emission zone (LEZ)","Düşük emisyon bölgesi (LEZ) sonu","Z","F118","Einde van een lage emissiezone."),
('row','F119'):("Begin of an airport area","Havalimanı bölgesi başlangıcı","Z","F119","Begin van een luchthavengebied."),
('row','F120'):("End of an airport area","Havalimanı bölgesi sonu","Z","F120","Einde van een luchthavengebied."),
('left',20):("Shared scooters/vehicles (motorised personal transporters) panel","Paylaşımlı (scooter türü) taşıyıcı alt levhası","S","M21: Voortbewegingstoestellen.","M21 voortbewegingstoestellen"),
('left',21):("Shared (rental) scooters panel","Paylaşımlı (kiralık) scooter alt levhası","S","M22: Deelvoortbewegingstoestellen.","M22 deelvoortbewegingstoestellen"),
('left',22):("Shared bicycles panel","Paylaşımlı bisiklet alt levhası","S","M23: Deelfietsen.","M23 deelfietsen"),
('left',23):("Shared bicycles and shared scooters panel","Paylaşımlı bisiklet ve scooter alt levhası","S","M24","M24 deelfietsen en deelvoortbewegingstoestellen"),
('left',27):("Begin of a zone: parking only for vehicles up to 3.5 t","Bölge başlangıcı: park yalnız en çok 3,5 t araçlar için","Z","Zone levhası: bölge içinde levha tekrarlanmaz; bölge sonu levhasında biter.","Begin zone parkeren voor voertuigen ≤ 3,5 ton."),
('left',28):("End of zone: parking for vehicles up to 3.5 t","Bölge sonu: park (≤ 3,5 t) kuralı biter","Z","","Einde zone parkeren ≤ 3,5 ton."),
('left',29):("Begin of blue zone (limited parking time, disc)","Mavi bölge başlangıcı (süreli park, park diski)","Z","Park diski gerekir: genelde 9–18 arası ve en çok 2 saat.","Begin zone met beperkte parkeertijd (blauwe zone)."),
('left',30):("End of blue zone","Mavi bölge sonu","Z","","Einde zone met beperkte parkeertijd."),
('left',31):("Begin of zone: no overtaking (left) of multi-wheeled vehicles","Bölge başlangıcı: sollama yasağı","Z","","Begin zone inhaalverbod."),
('left',32):("End of zone: no overtaking","Bölge sonu: sollama yasağı biter","Z","","Einde zone inhaalverbod."),
('left',33):("Begin of zone: entry forbidden to vehicles heavier than shown","Bölge başlangıcı: gösterilen tonajdan ağır araçlar giremez","Z","","Begin zone toegang verboden > massa."),
('left',34):("End of zone: weight limit","Bölge sonu: tonaj sınırı biter","Z","","Einde zone massa."),
('left',35):("Begin of a zone with speed limit (70)","Hız sınırlı bölge başlangıcı (70)","Z","Kavşakta bitmez; 'bölge sonu' levhasında biter.","Begin zone snelheidsbeperking."),
('left',36):("End of a zone with speed limit","Hız sınırlı bölge sonu","Z","","Einde zone snelheidsbeperking."),
('left',39):("Begin of a zone: no parking (certain hours)","Bölge başlangıcı: park yasak (belirli saatlerde)","Z","","Begin zone parkeerverbod."),
('left',55):("No parking from the 1st to the 15th of the month","Ayın 1'inden 15'ine kadar park yasak","E","E5: Bu tarafta 1–15'i arası park yasak; diğer tarafa park et.","E5 Parkeerverbod 1e–15e."),
('left',56):("No parking from the 16th to the end of the month","Ayın 16'sından sonuna kadar park yasak","E","E7: Bu tarafta 16–ay sonu park yasak.","E7 Parkeerverbod 16e–einde."),
('left',58):("Panel: except residents (exempt)","Alt levha: sakinler hariç","S","'Uitgez. bewoners': Bölge sakinlerinin (kartı olanların) istisnası.","Uitgezonderd bewoners."),
('left',59):("Panel: paying parking (pay & display)","Alt levha: ücretli park (betalend)","S","Ücretli park kartı/otomatı gerekir.","Betalend."),
('left',61):("Parking reserved for bicycles and motorcycles (time-based)","Park: belirli saatlerde bisiklet ve motosiklet için ayrılmış","E","E9j","E9j"),
('left',64):("Parking reserved for persons with disabilities","Park yalnız engelli kartı olanlar için","E","Engelli kartı olmayan park edemez.","P + rolstoel."),
('left',65):("Parking reserved for vehicles with parking card","Park: park kartı olan araçlar için","E","","P + parkeerkaart."),
('left',66):("Parking reserved for residents","Park: sakinlere ayrılmış","E","","P + bewoners."),
('left',67):("Parking reserved for car sharing","Park: araç paylaşımı (autodelen) için","E","","P + autodelen."),
('left',71):("Loading and unloading bay","Yükleme-boşaltma alanı","E","Sadece yük yüklemek/boşaltmak için, süre kısıtlıdır.","Laden en lossen."),
('left',76):("Alternate half-month parking in the whole built-up area","Yerleşim yerinde ayın yarısına göre dönüşümlü park","E","E11: 1–15'i tek numaralı ev tarafı, 16–ay sonu çift numaralı ev tarafı; kayış değişimi 19:30–20:00.","E11 Halfmaandelijks parkeren."),
('left',82):("Airport","Havalimanı","I","S.1 pictogram.","Luchthaven."),
('left',83):("Fair / exhibition hall","Fuar / sergi salonu","I","S.2","Beurs- of tentoonstellingshal."),
('left',84):("Port","Liman","I","S.3","Haven."),
('left',85):("Car ferry","Araba vapuru","I","S.4","Car-ferry."),
('left',86):("Business and industrial park","İş ve sanayi bölgesi","I","S.5","Bedrijf en industriepark."),
('left',87):("Police services","Polis","I","S.10","Politiediensten."),
('left',88):("Fire brigade","İtfaiye","I","S.11","Brandweer."),
('left',89):("Civil protection","Sivil koruma","I","S.12","Civiele bescherming."),
('left',90):("Cemetery","Mezarlık","I","S.13","Begraafplaats."),
('left',91):("Bus station","Otobüs terminali","I","S.14","Busstation."),
('left',92):("Train station","Tren istasyonu","I","S.15","Treinstation."),
('left',93):("Road station (truck stop)","Yol istasyonu (TIR durağı)","I","S.16","Wegstation."),
('left',94):("Town hall","Belediye binası","I","S.17","Stadhuis of gemeentehuis."),
('left',95):("Place of worship","İbadet yeri","I","S.18","Plaats voor eredienst."),
('left',96):("Court house","Adliye","I","S.19","Gerechtsgebouw."),
('left',97):("Car sleeper train","Araç yataklı treni","I","S.20","Auto-slaaptrein."),
('left',98):("Post office","Postane","I","S.21","Postkantoor."),
('left',100):("Recommended cycling route (blue signpost)","Önerilen bisiklet güzergâhı (mavi tabela)","I","F34b: Bisiklet rotası.","Wegwijzer: aanbevolen reisweg voor fietsers."),
('left',102):("Recommended tourist cycling route (brown signpost)","Önerilen turistik bisiklet güzergâhı (kahverengi)","I","F34c","Aanbevolen reisweg naar toeristische bestemming."),
('left',103):("Sports centre, stadium","Spor merkezi, stadyum","I","S.30","Sportcentrum, stadion."),
('left',104):("Castle","Kale","I","S.31","Kasteel."),
('left',105):("Ruins","Harabe","I","S.32","Ruïnes."),
('left',106):("Monastery, abbey","Manastır, abbey","I","S.33","Klooster, abdij."),
('left',107):("Cultural park, recreation park","Kültür parkı, eğlence parkı","I","S.34","Cultureel park, recreatiepark."),
('left',108):("Monument and remarkable landscape","Anıt ve görülmeye değer manzara","I","S.35 (örnek: Atomium).","Monument."),
('left',109):("Nature park","Doğa parkı","I","S.36","Natuurpark."),
('left',110):("Emergency exit to the left (tunnel), 100 m","Acil çıkış solda, 100 m (tünel)","I","F52bis: Kaçış yolu.","Vluchtroute."),
('left',111):("Emergency exit to the right (tunnel), 100 m","Acil çıkış sağda, 100 m (tünel)","I","F52bis","Vluchtroute."),
('left',112):("Petrol station","Benzin istasyonu","I","F63","Tankstation."),
('left',113):("Petrol station with LPG","LPG'li benzin istasyonu","I","F63","Tankstation LPG."),
('left',114):("Petrol station with CNG","CNG'li istasyon","I","F63","Tankstation CNG."),
('left',115):("Petrol station with LNG","LNG'li istasyon","I","F63","Tankstation LNG."),
('left',116):("Hydrogen station","Hidrojen istasyonu","I","F63","Tankstation waterstof."),
('left',117):("Electric charging station","Elektrikli şarj istasyonu","I","F63","Laadstation."),
}
