# (tr, cat, note) for docx entries 1..222. cat: W warning, P priority, C prohibition, D mandatory, E parking, I info, Z zone, S sub-panel
DX = {
1:("Özel bir işareti olmayan tehlike uyarısı","W","A51: Altındaki levha tehlikenin ne olduğunu yazar."),
2:("Alçaktan uçan uçaklar uyarısı","W","A35: Uçakların çok alçaktan geçtiği yer (havalimanı yakını)."),
3:("Yolda sığır/hayvan sürüsü geçişi uyarısı","W","A29: Çiftlik hayvanları (sığır) yolu geçebilir."),
4:("Vahşi hayvan (geyik) geçişi uyarısı","W","A27: Orman kenarlarında; yavaşla, hayvan aniden çıkabilir."),
5:("Açılır köprü uyarısı","W","A9: Köprü açılırsa durmak zorunda kalabilirsin."),
6:("Kasis / yol tümseği uyarısı","W","A14: Tümsekten önce yavaşla."),
7:("Bozuk / dalgalı yol yüzeyi uyarısı","W","A13: Yolda çukur veya tümsek (ezelsrug) var."),
8:("Çocuklar uyarısı (okul/oyun alanı)","W","A23: Çocukların çok bulunduğu yer; hızını düşür."),
9:("Sağdan gelene öncelik olan kavşak","P","B17: Bu kavşakta öncelik SAĞDAN GELENDEDİR. Levha sadece hatırlatmadır, kural levha olmasa da geçerlidir."),
10:("Yol ver (ters üçgen)","P","B1: Gerekirse dur, ama zorunlu tam duruş yok. Sınavda B5 (STOP) ile karıştırılır."),
11:("Kavşak: solda yan yol (önceliğin sende olduğu kavşak)","P","B15 türevi: Üçgendeki kalın çizgi senin ana yolun, ince çizgi yan yol. Önceliğin vardır."),
12:("Kavşak: solda keskin yan yol (önceliğin sende)","P","B15 türevi: Yan yol sola ve açılı bağlanır; ana yolda önceliğin var."),
13:("Kavşak: sağda yan yol (önceliğin sende)","P","B15 türevi: Sağdan bağlanan yan yola karşı önceliğin var."),
14:("Kavşak: sağda keskin yan yol (önceliğin sende)","P","B15 türevi: Yan yol sağdan ve açılı bağlanır; önceliğin var."),
15:("Kavşak: iki yanda yan yol (önceliğin sende)","P","B15: Her iki yandan gelen yan yollara karşı önceliğin var."),
16:("DUR ve yol ver","P","B5: Trafik olmasa bile TAM DURUŞ zorunlu, sonra yol ver. Durma çizgisinde dur."),
17:("Kuvvetli yan rüzgâr uyarısı","W","A37: Köprü/açık alanda araç sürüklenebilir; direksiyonu sıkı tut."),
18:("Sola viraj uyarısı","W","A1a: Virajdan ÖNCE yavaşla (virajda değil)."),
19:("Çift viraj uyarısı, önce sola","W","A1c: Önce sola sonra sağa; iki ya da daha fazla viraj dizisi."),
20:("Sağa viraj uyarısı","W","A1b"),
21:("Çift viraj uyarısı, önce sağa","W","A1d: Önce sağa sonra sola."),
22:("Bisikletliler uyarısı","W","A25: Bisiklet yolundan yola çıkış/geçiş noktası; bisikletliler yola girebilir."),
23:("Taş düşme tehlikesi uyarısı","W","A19"),
24:("Yolda gevşek çakıl/çakıl savrulması uyarısı","W","A17: Lastiklerden çakıl fırlayabilir; mesafeyi koru, yavaşla."),
25:("Yaya geçidi uyarısı","W","A21: Yayalar geçebilir; yavaşla, durmaya hazır ol."),
26:("Rıhtım veya nehir kıyısı uyarısı","W","A11: Yol suya çıkıyor, korkuluk olmayabilir."),
27:("Yol daralması uyarısı (iki taraftan)","W","A7a"),
28:("Soldan yol daralması uyarısı","W","A7b"),
29:("Sağdan yol daralması uyarısı","W","A7c"),
30:("Yol çalışması uyarısı","W","A31: Hızını düşür, işçilere dikkat."),
31:("Kaygan yol uyarısı","W","A15: Islak/buzlu/yağlı yol; yavaşla, ani fren yapma."),
32:("Dik yokuş çıkış uyarısı","W","A5: %10 gibi eğim; vitesi düşür."),
33:("Dik yokuş iniş uyarısı","W","A3: Motor freni için vitesi düşür; sürekli frene basma."),
34:("Trafik ışığı uyarısı","W","A33: İleride ışıklı kavşak/geçit var."),
35:("Bariyersiz demiryolu geçidi uyarısı","W","A43: Bariyer ve ışık yok; kendin bakıp geç."),
36:("Bariyerli demiryolu geçidi uyarısı","W","A41: Bariyer var; bariyer kapanıyorsa/kapalıysa geçme."),
37:("Tek hatlı demiryolu geçidi (Andreas haçı)","W","A45: Geçidin hemen yanında; tek hat."),
38:("Çok hatlı (2+) demiryolu geçidi (Andreas haçı)","W","A47: İki veya daha fazla hat; bir tren geçse bile diğeri gelebilir."),
39:("Tramvay uyarısı","W","A49: Yolda raylı tramvay geçişi var; tramvay HER ZAMAN önceliklidir."),
40:("Çift yönlü trafik uyarısı","W","A39: Tek yönlü yoldan sonra iki yönlü kısım başlıyor."),
41:("Giriş yasak (her yönde, her araç)","C","C3: Hiçbir sürücü giremez (iki yönde)."),
42:("Otobüs giremez","C","C22: Otobüs ve yolcu otobüsleri (autocar) giremez."),
43:("Otomobil giremez","C","C5: İkiden fazla tekerlekli motorlu araçlar giremez."),
44:("Bisiklet giremez","C","C11"),
45:("Bisiklet ve moped giremez","C","C11 + C9 birleşik görünümlü levha."),
46:("Girilmez / yasak yön (tek yönlü yola ters giriş)","C","C1: Kırmızı daire, beyaz yatay çubuk = bu yönde giremezsin."),
47:("El arabası giremez","C","C17"),
48:("At arabası (atlı araç) giremez","C","C13"),
49:("Binici (atlı) giremez","C","C15"),
50:("Moped giremez","C","C9: Yalnız mopedler; bisiklet değil."),
51:("Moped, motosiklet ve otomobil giremez","C","C5 benzeri: motorlu tüm taşıtlar yasak."),
52:("Motosiklet giremez","C","C7"),
53:("Motosiklet ve otomobil giremez","C","İki ve daha çok tekerlekli motorlu araçlar."),
54:("Yaya giremez","C","C19"),
55:("ATV / dört tekerlekli arazi aracı (quad) giremez","C","C6"),
56:("Kamyon giremez","C","C23: Yük taşımak için tasarlanmış motorlu araçlar."),
57:("Sollama yasağı","C","C35: Bir sonraki kavşağa kadar iki+ tekerlekli motorlu araç/at arabasını SOLDAN sollama yasak."),
58:("Sollama yasağının sonu","C","C37"),
59:("Kamyonlar için sollama yasağı","C","C39: Yük taşıyıcı >3,5 t araçlar için."),
60:("Kamyonlar için sollama yasağının sonu","C","C41"),
61:("Hız sınırı başlangıcı","C","C43: Yazan hız (ör. 50) geçmeyi yasaklar. Bir sonraki kavşakta veya başka C43'te biter."),
62:("Hız sınırının sonu","C","C45: Hız sınırı biter; yine de genel hız limitleri geçerli."),
63:("Hız sınırlı bölgenin başlangıcı (ZONE 30 vb.)","Z","F4a / bölge levhası: Kavşaklarda bitmez; sadece 'bölge sonu' levhasıyla biter."),
64:("Hız sınırlı bölgenin sonu","Z","F4b: Bölge sona erdi."),
65:("Sola dönüş yasak","C","C31a"),
66:("Sağa dönüş yasak","C","C31b"),
67:("U dönüşü yasak","C","C33: Bir sonraki kavşağa kadar U dönüşü yok."),
68:("Tehlikeli madde taşıyan araçlar giremez","C","C24a"),
69:("Patlayıcı/yanıcı madde taşıyan araçlar giremez","C","C24b"),
70:("Belirtilenden yüksek araçlar giremez","C","C29: Yükseklik (yük dahil)."),
71:("Belirtilenden uzun araçlar giremez","C","C25: Uzunluk (yük dahil)."),
72:("Kirletici sıvı taşıyan araçlar giremez","C","C24c: Su kirleten maddeler."),
73:("Belirtilenden ağır araçlar giremez","C","C21: Yüklü ağırlık sınırı (ör. 5,5 t)."),
74:("Belirtilenden geniş araçlar giremez","C","C27"),
75:("Park yasak","E","E1: Tek çizgi = park yasak (durmak serbest)."),
76:("Durmak ve park yasak","E","E3: İki çizgi (çarpı) = durmak da park etmek de yasak."),
77:("Dar geçit: karşıdan gelene yol ver","P","B19: Karşıdan gelenlere öncelik vermelisin (kırmızı ok senin yönün)."),
78:("Sola dönmek zorunlu","D","D1"),
79:("Sağa dönmek zorunlu","D","D1"),
80:("Soldan geçmek zorunlu (engelin solundan)","D","D1"),
81:("Sağdan geçmek zorunlu (engelin sağından)","D","D1"),
82:("Dönel kavşakta zorunlu dönüş yönü","D","D5: Giriş yolunda B1/B5 ile birlikte; kavşaktakilere yol ver."),
83:("Düz gitmek veya sola dönmek zorunlu","D","D3"),
84:("Düz gitmek veya sağa dönmek zorunlu","D","D3"),
85:("Zorunlu yön: sol","D","D1"),
86:("Zorunlu yön: sağ","D","D1"),
87:("Zorunlu yön: düz","D","D1"),
88:("Bisikletliler için zorunlu yol (bisiklet yolu)","D","D7: Bisikletliler kullanmak ZORUNDA; araçlar giremez."),
89:("Yayalar ve bisikletliler için ayrılmış zorunlu yol","D","D9/D10 türevi: Çizgiyle ayrılmış, her biri kendi tarafında."),
90:("Binici (atlı) yolu","D","D13"),
91:("Yayalar için zorunlu yol","D","D11"),
92:("Yaya ve bisikletliler için ortak zorunlu yol","D","D10: Birlikte kullanırlar; hız 30 km/h'ı geçmez."),
93:("Yerleşim yeri (köy/şehir) başlangıcı","I","F1: Genelde 50 km/h başlar (Brüksel hariç: 30)."),
94:("Yerleşim yeri sonu","I","F3: Üstü çizili isim = yerleşim sonu; hız sınırı artar (Flaman: 70)."),
95:("Kasis / yükseltilmiş yol bölümü","I","F87: Önce yavaşla."),
96:("Bisiklet geçidi","I","F50: Bisikletlilere yol ver; yayalar/bisikletliler geçiyor."),
97:("Yaya geçidi","I","F49: Geçitteki yayalara öncelik ver. Geçide ve 5 m öncesine park/durma yasak."),
98:("Bisikletliler için bekleme kutusu (bike box)","I","F14: Işıkta bisikletliler öne geçer; arabalar çizginin gerisinde durur."),
99:("Çıkmaz sokak","I","F45: Başka çıkışı yoktur."),
100:("Kavşak yönlendirme tabelası (varış yönleri)","I","F27: Kavşakta hangi yöne hangi şehir; öncesinden doğru şeride geç."),
101:("Kaçış rampası (freni tutmayan kamyonlar için)","I","F95: Uzun inişte freni boşalan araçlar içindir; ASLA park etme."),
102:("Otoyol benzeri yol (autoweg) başlangıcı","I","F9: Otoyol kuralları (yaya/bisiklet yasak, durma-park yasak) geçerli; kavşak olabilir, min. hız yok."),
103:("Otoyol benzeri yol (autoweg) sonu","I","F11"),
104:("Otobüs şeridi","I","F17: Yalnız otobüsler (ve levhada gösterilenler)."),
105:("Otobüs ve tramvay şeridi","I","F17: Otobüs ve tramvay; araçlara kapalı."),
106:("Bisiklet şeridi / bisiklet bölgesi (fietszone) başlangıcı","Z","F111: Max 30 km/h; bisikletliyi sollama; tek yönlüde tüm yol bisikletlinin."),
107:("Bisiklet bölgesi (fietszone) sonu","Z","F113"),
108:("Şerit yönleri genel görünümü","I","F13: Şeritlere göre izlenecek yönler."),
109:("Şerit sonu (birleşme)","I","F? Şerit bitiyor; fermuar sistemi (sırayla geç) uygula."),
110:("Şeride göre azami hız","I","F89: Her şeridin ayrı hız sınırı vardır."),
111:("Otoyol başlangıcı","I","F5: Otoyol kuralları: min. 70 km/h, durmak/park yasak, yaya/bisiklet/moped/traktör yasak."),
112:("Otoyol sonu","I","F7"),
113:("Tek yönlü yol","I","F19"),
114:("Park izni (park yeri)","E","E9a: Park serbest."),
115:("Park yalnız kısmen yolda (iki tekerlek kaldırımda)","E","E9f: Aracın bir kısmı kaldırım/banket üzerinde olacak şekilde park."),
116:("Park yalnız yolda (yolun içinde)","E","E9g: Kaldırıma çıkmadan yolda park."),
117:("Park yalnız banket/kaldırım üzerinde","E","E9e: Tüm tekerlekler kaldırım/banket üzerinde."),
118:("Yaya bölgesi başlangıcı","Z","F103: Yaya bölgesi; motorlu araç girişi yasak (istisnalar levhada)."),
119:("Yaya bölgesi sonu","Z","F105"),
120:("Öncelikli yol başlangıcı","P","B9: Sarı baklava; öncelik sende. HER kavşaktan sonra tekrarlanmalı."),
121:("Öncelikli yol sonu","P","B11: Bu levhadan sonra sağdan gelen öncelik kuralı yine geçerli."),
122:("Woonerf / erf (yerleşik alan) başlangıcı","Z","F12a: Max 20 km/h, yayalar tüm yolu kullanır, çocuklar oynayabilir, park sadece belirli yerlerde."),
123:("Woonerf / erf (yerleşik alan) sonu","Z","F12b"),
124:("Öncelikli yolun virajı (ana yol dönüyor)","P","B9 bağlantılı: Öncelikli yol kavşakta dönüyor; yön değiştirenler dikkat."),
125:("Dar geçit: karşıdan gelenler yol vermeli","P","B21: Önceliğin sende."),
126:("Ulusal hız sınırları levhası","I","Bölgede genel hız limitleri (50/70/90/120) özet olarak gösterilir."),
127:("Tünel başlangıcı","I","F8: Uzun tünelde (500 m üzeri) uzunluk altta yazar; kısa farlar yak."),
128:("Tek yönlü yol (bisikletliler hariç, ters yönde girebilir)","P","F19 + M levha: Bisikletliler ters yönden girebilir."),
129:("Tek yönlü yol (bisiklet ve A sınıfı moped ters yönde girebilir)","P","F19 + M levha."),
130:("Öncelikli yol sonu, 200 m ileride","P","B13: 200 m sonra B11 gelecek."),
131:("Sola dönüş zorunlu, bisiklet ve A moped hariç","D","D1 + M levha."),
132:("Bisikletliler ve B sınıfı moped için zorunlu yol","D","D7 + 'B verplicht' levhası: B moped bu yolu kullanmak zorunda."),
133:("Bisikletliler için zorunlu yol, B moped YASAK","D","D7 + 'B verboden' levhası."),
134:("Giriş yasak, bisikletliler hariç","C","C1 + 'uitgezonderd' levhası: Bisikletliler ters yönde girebilir."),
135:("Giriş yasak, bisikletli ve A moped hariç","C","C1 + M levha."),
136:("Her iki yönde giriş yasak, bisikletliler hariç","C","C3 + M levha."),
137:("Her iki yönde giriş yasak, bisiklet ve A moped hariç","C","C3 + M levha."),
138:("Her iki yönde giriş yasak, yerel trafik hariç","C","C3 + 'plaatselijk verkeer': sadece oraya gidenler girebilir."),
139:("Giriş yasak, oyun sokağı (speelstraat)","C","C3 + 'speelstraat': Çocuk oyun sokağı; araç giremez (istisnalar hariç)."),
140:("Sola dönüş yasak, bisikletliler hariç","C","C31a + M levha."),
141:("Sola dönüş yasak, bisiklet ve A moped hariç","C","C31a + M levha."),
142:("Yol verme: bisikletliler yol vermeli","P","B1 + M levha: Bisikletliler yol vermeli (sen değil)."),
143:("Bisikletliler ve mopedler yol vermeli","P","B1 + M levha."),
144:("Yol ver, 50 m ileride","P","B3: 50 m sonra B1 geliyor."),
145:("DUR ve yol ver, 250 m ileride","P","B7: 250 m sonra B5 (STOP) geliyor."),
146:("Yol ver, soldan ve sağdan gelen bisikletlilere dikkat","P","B1 + M levha: Bisikletliler iki yönde gelir; yol vermelisin."),
147:("Yol ver, soldan ve sağdan gelen bisiklet/mopedlere dikkat","P","B1 + M levha."),
148:("Bisikletliler DUR ve yol vermeli","P","B5 + M levha: STOP bisikletliler için."),
149:("Bisikletliler ve mopedler DUR ve yol vermeli","P","B5 + M levha."),
150:("DUR ve yol ver, 50 m ileride","P","B7: 50 m sonra STOP."),
151:("DUR, soldan ve sağdan gelen bisikletlilere dikkat","P","B5 + M levha."),
152:("DUR, soldan ve sağdan gelen bisiklet/mopedlere dikkat","P","B5 + M levha."),
153:("Kontrolsüz kavşak (sağdan öncelik), bisikletliler iki yönden gelir","P","B17 + M levha."),
154:("Kontrolsüz kavşak (sağdan öncelik), bisiklet ve mopedler iki yönden gelir","P","B17 + M levha."),
155:("Engelliler için (alt levha)","S","Park yeri engelli kartı olanlara ayrılmıştır."),
156:("Kişisel taşıyıcılar (scooter vb.) için (alt levha)","S","Tek kişilik elektrikli/itmeli taşıyıcılar için geçerli."),
157:("Bisikletliler için (alt levha)","S","Üstteki levha bisikletliler için geçerli."),
158:("Bisikletliler ve mopedler için (alt levha)","S","Üstteki levha hem bisiklet hem moped için."),
159:("Bisiklet ve P sınıfı moped (Speed pedelec) için (alt levha)","S","Hızlı pedelec = P sınıfı."),
160:("P sınıfı moped (speed pedelec) için (alt levha)","S","Sadece hızlı pedelekler."),
161:("Elektrikli araçlar için (alt levha)","S","Şarj noktası: park yeri elektrikli araçlara ayrılmış."),
162:("Araç paylaşımı / carpool için (alt levha)","S","Carpool şeridi/park."),
163:("Taksiler için (alt levha)","S","Taksi şeridi/park yeri."),
164:("İstisna: bisikletliler (alt levha)","S","'Uitgezonderd' = hariç; yasak bisikletliler için geçerli değil."),
165:("İstisna: bisikletliler (alt levha)","S","'Excepte' = hariç (Fransızca)."),
166:("İstisna: bisiklet ve mopedler (alt levha)","S","Bisiklet ve mopedler yasaktan muaf."),
167:("İstisna: bisiklet ve A sınıfı moped (alt levha)","S","A sınıfı moped (max 25 km/h)."),
168:("İstisna: bisiklet ve P moped (alt levha)","S","P = speed pedelec."),
169:("İstisna: bisiklet ve A, P moped (alt levha)","S",""),
170:("İstisna: A sınıfı moped (alt levha)","S","'Excepte A'."),
171:("İstisna: en az 2 kişilik araçlar (alt levha)","S","'Uitgezonderd 2+': 2 veya daha çok yolcusu olan araçlar (carpool şeridi)."),
172:("İstisna: otobüsler (alt levha)","S","'Uitgez. bus'."),
173:("İstisna: izinliler ve teslimat araçları (alt levha)","S","Vergunninghouders ve leveranciers."),
174:("İstisna: yerel trafik (alt levha)","S","Plaatselijk verkeer: oraya gidenler."),
175:("B sınıfı moped zorunlu (alt levha)","S","'B verplicht'."),
176:("P sınıfı moped zorunlu (alt levha)","S","'P verplicht'."),
177:("B veya P sınıfı moped zorunlu (alt levha)","S",""),
178:("B sınıfı moped zorunlu (Fransızca alt levha)","S","'B obligatoire'."),
179:("B sınıfı moped yasak (alt levha)","S","'B verboden'."),
180:("P sınıfı moped yasak (alt levha)","S",""),
181:("B veya P sınıfı moped yasak (alt levha)","S",""),
182:("B sınıfı moped yasak (Fransızca alt levha)","S","'B interdit'."),
183:("Bisikletliler her iki yönde (alt levha)","S","Tek yönlü yolda bisikletliler çift yönde gidebilir."),
184:("Bisiklet ve mopedler her iki yönde (alt levha)","S",""),
185:("Bisikletliler her iki yönden gelir (alt levha)","S","Bisikletliler yan yolda iki yönden gelebilir."),
186:("Bisiklet ve mopedler iki yönden gelir (alt levha)","S",""),
187:("A sınıfı moped ve bisiklet iki yönden (alt levha)","S",""),
188:("P sınıfı moped ve bisiklet iki yönden (alt levha)","S",""),
189:("A ve P sınıfı moped + bisiklet iki yönden (alt levha)","S",""),
190:("Alt levha: ... metre sonra başlar","S","Kuralın başlayacağı mesafe."),
191:("Alt levha: kural başlıyor (ok yukarı)","S","Yön oku: kuralın başlangıcı."),
192:("Alt levha: kural geçerli (çift ok)","S","Bu yoldaki ara kısımda geçerli."),
193:("Alt levha: kural sona eriyor (ok aşağı)","S","Kuralın bitişi."),
194:("Alt levha: ... metre ileride","S","Tehlike/levha bu mesafede."),
195:("Alt levha: ... metre ileride STOP","S","Mesafede stop gelir."),
196:("Alt levha: ... km boyunca","S","Kuralın uzunluğu (km)."),
197:("Alt levha: +3 ton","S","3 tonun üzerindeki araçlar için."),
198:("Alt levha: +5 ton","S",""),
199:("Alt levha: +7 ton","S",""),
200:("Alt levha: kavşak şekli","S","Kavşağın şeklini gösterir."),
201:("Alt levha: Park + Ride (P+R)","S","Park et ve toplu taşımaya bin."),
202:("Alt levha: park diski","S","Park diski kullanılmak zorunda."),
203:("Alt levha: gösterilen saatlerde","S","Örn. 7–19 saatleri arası."),
204:("Alt levha: ... dakika için","S","Park süresi sınırı (örn. 30 dk)."),
205:("Alt levha: okul sokağı (schoolstraat)","S","C3 + 'schoolstraat': Belirtilen saatlerde motorlu araç giremez (izinliler ve acil araçlar hariç, yaya hızıyla)."),
206:("Alt levha: acil telefon ve yangın söndürücü","S",""),
207:("Alt levha: olası kuyruk (file mogelijk)","S","Önünde kuyruk oluşabilir."),
208:("Alt levha: tekrar (herhaling)","S","Önceki levhanın tekrarıdır."),
209:("Alt levha: bozuk yol yüzeyi","S","Verformd wegdek."),
210:("Alt levha: uzunlamasına oluklar (langsgroeven)","S","Motosikletler için tehlikeli yüzey."),
211:("Alt levha: yumuşak banket (zachte berm)","S","Banketi kullanma."),
212:("Alt levha: teker izi (spoorvorming)","S",""),
213:("Alt levha: sis (mist)","S","Sis olasılığı."),
214:("Alt levha: buzlanma (kar tanesi)","S","Buz tehlikesi."),
215:("Alt levha: su kayması (aquaplaning)","S","Yağmurda aracın suyun üzerinde kayma riski."),
216:("Alt levha: ıslak yol (bij nat wegdek)","S","Islak yolda tehlike."),
217:("Alt levha: kamyon çıkışı","S","Kamyonlar yola çıkabilir."),
218:("Alt levha: sanayi bölgesi","S","Bu yoldaki hareketlilik sanayiden."),
219:("Tünel kategorisi B (alt levha)","S","Tehlikeli madde (ADR) tünel kategorileri; B: en az kısıtlı."),
220:("Tünel kategorisi C (alt levha)","S",""),
221:("Tünel kategorisi D (alt levha)","S",""),
222:("Tünel kategorisi E (alt levha)","S","E: tehlikeli maddeler için en kısıtlı."),
}
